/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import model.Penumpang;
import service.TransaksiManagerDB;

/**
 *
 * @author user
 */
public class DashboardFormNew extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFormNew.class.getName());

    /**
     * Creates new form DashboardFormNew
     */
    private final Penumpang penumpang;

    private boolean isSidebarVisible = true;

    public DashboardFormNew(Penumpang penumpang) {
        initComponents();
        this.penumpang = penumpang;
        setLocationRelativeTo(null);
        tampilkanData();
    }

    private void tampilkanData() {
        JLabelUsername.setText("" + penumpang.getUsername());
        jLabelGreenPoints.setText(penumpang.getGreenPoints() + " PTS");

        double totalBayar = TransaksiManagerDB.totalBiaya(penumpang.getIdUser());
        double totalEmisi = TransaksiManagerDB.totalEmisi(penumpang.getIdUser());

        jLabelTotalPembayaran.setText("Rp " + String.format("%,.0f", totalBayar));
        jLabelCarbonSaving.setText(String.format("%.2f", totalEmisi) + " kg CO₂");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBarPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnLogout5 = new javax.swing.JButton();
        MenuDashboard = new javax.swing.JPanel();
        lblDashboard5 = new javax.swing.JLabel();
        JLabelUsername = new javax.swing.JLabel();
        jLabelRole = new javax.swing.JLabel();
        MenuHitungTarif = new javax.swing.JPanel();
        lblDashboardHitungTarif = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jPanelHeaderDashboard = new javax.swing.JPanel();
        jLabelHeading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SidebarToggleButton = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        jPanelCardFrame = new javax.swing.JPanel();
        GreenPointCard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelGreenPoints = new javax.swing.JLabel();
        CarbonSavingCard = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCarbonSaving = new javax.swing.JLabel();
        TotalPembayaranCard = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelTotalPembayaran = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setBackground(new java.awt.Color(0, 102, 51));

        btnLogout5.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout5.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout5.setText("Logout");
        btnLogout5.addActionListener(this::btnLogout5ActionPerformed);

        MenuDashboard.setBackground(new java.awt.Color(0, 153, 102));
        MenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDashboardMouseClicked(evt);
            }
        });

        lblDashboard5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDashboard5.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard5.setText("Dashboard");
        lblDashboard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboard5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuDashboardLayout = new javax.swing.GroupLayout(MenuDashboard);
        MenuDashboard.setLayout(MenuDashboardLayout);
        MenuDashboardLayout.setHorizontalGroup(
            MenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuDashboardLayout.setVerticalGroup(
            MenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JLabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        JLabelUsername.setText("Admin");

        jLabelRole.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelRole.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRole.setText("Selamat datang");

        MenuHitungTarif.setBackground(new java.awt.Color(0, 102, 51));
        MenuHitungTarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHitungTarifMouseClicked(evt);
            }
        });

        lblDashboardHitungTarif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDashboardHitungTarif.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboardHitungTarif.setText("Hitung Tarif");
        lblDashboardHitungTarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardHitungTarifMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuHitungTarifLayout = new javax.swing.GroupLayout(MenuHitungTarif);
        MenuHitungTarif.setLayout(MenuHitungTarifLayout);
        MenuHitungTarifLayout.setHorizontalGroup(
            MenuHitungTarifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHitungTarifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboardHitungTarif)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuHitungTarifLayout.setVerticalGroup(
            MenuHitungTarifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuHitungTarifLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDashboardHitungTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuHitungTarif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(JLabelUsername))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnLogout5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelRole)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(JLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRole)
                .addGap(17, 17, 17)
                .addComponent(MenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuHitungTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 398, Short.MAX_VALUE)
                .addComponent(btnLogout5)
                .addContainerGap())
        );

        javax.swing.GroupLayout SideBarPanelLayout = new javax.swing.GroupLayout(SideBarPanel);
        SideBarPanel.setLayout(SideBarPanelLayout);
        SideBarPanelLayout.setHorizontalGroup(
            SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SideBarPanelLayout.setVerticalGroup(
            SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(SideBarPanel, java.awt.BorderLayout.WEST);

        jPanelContent.setBackground(new java.awt.Color(240, 244, 241));
        jPanelContent.setPreferredSize(new java.awt.Dimension(700, 508));
        jPanelContent.setLayout(new java.awt.BorderLayout(20, 0));

        jPanelHeaderDashboard.setBackground(java.awt.Color.white);
        jPanelHeaderDashboard.setPreferredSize(new java.awt.Dimension(700, 80));

        jLabelHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelHeading.setForeground(new java.awt.Color(27, 77, 62));
        jLabelHeading.setText("SmartFare Dashboard");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(189, 195, 199));

        SidebarToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/hamburger (1) (1).png"))); // NOI18N
        SidebarToggleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SidebarToggleButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelHeaderDashboardLayout = new javax.swing.GroupLayout(jPanelHeaderDashboard);
        jPanelHeaderDashboard.setLayout(jPanelHeaderDashboardLayout);
        jPanelHeaderDashboardLayout.setHorizontalGroup(
            jPanelHeaderDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderDashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(SidebarToggleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHeading)
                .addGap(36, 407, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanelHeaderDashboardLayout.setVerticalGroup(
            jPanelHeaderDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHeaderDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelHeading)
                    .addComponent(SidebarToggleButton))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelContent.add(jPanelHeaderDashboard, java.awt.BorderLayout.NORTH);

        Container.setLayout(new java.awt.BorderLayout());

        jPanelCardFrame.setBackground(new java.awt.Color(244, 246, 249));
        jPanelCardFrame.setPreferredSize(new java.awt.Dimension(700, 200));
        jPanelCardFrame.setLayout(new java.awt.GridLayout(3, 1, 25, 20));

        GreenPointCard.setBackground(java.awt.Color.red);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Green Points");

        jLabelGreenPoints.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelGreenPoints.setText("Points");

        javax.swing.GroupLayout GreenPointCardLayout = new javax.swing.GroupLayout(GreenPointCard);
        GreenPointCard.setLayout(GreenPointCardLayout);
        GreenPointCardLayout.setHorizontalGroup(
            GreenPointCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenPointCardLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(GreenPointCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGreenPoints)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GreenPointCardLayout.setVerticalGroup(
            GreenPointCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GreenPointCardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(52, 52, 52)
                .addComponent(jLabelGreenPoints)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanelCardFrame.add(GreenPointCard);

        CarbonSavingCard.setBackground(java.awt.Color.green);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Carbon Saving");

        jLabelCarbonSaving.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCarbonSaving.setText("Carbon");

        javax.swing.GroupLayout CarbonSavingCardLayout = new javax.swing.GroupLayout(CarbonSavingCard);
        CarbonSavingCard.setLayout(CarbonSavingCardLayout);
        CarbonSavingCardLayout.setHorizontalGroup(
            CarbonSavingCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarbonSavingCardLayout.createSequentialGroup()
                .addGroup(CarbonSavingCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CarbonSavingCardLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelCarbonSaving))
                    .addGroup(CarbonSavingCardLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6)))
                .addContainerGap(586, Short.MAX_VALUE))
        );
        CarbonSavingCardLayout.setVerticalGroup(
            CarbonSavingCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarbonSavingCardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(55, 55, 55)
                .addComponent(jLabelCarbonSaving)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanelCardFrame.add(CarbonSavingCard);

        TotalPembayaranCard.setBackground(java.awt.Color.blue);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total Pembayaran");

        jLabelTotalPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTotalPembayaran.setText("Pembayaran");

        javax.swing.GroupLayout TotalPembayaranCardLayout = new javax.swing.GroupLayout(TotalPembayaranCard);
        TotalPembayaranCard.setLayout(TotalPembayaranCardLayout);
        TotalPembayaranCardLayout.setHorizontalGroup(
            TotalPembayaranCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPembayaranCardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(TotalPembayaranCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTotalPembayaran)
                    .addComponent(jLabel7))
                .addContainerGap(540, Short.MAX_VALUE))
        );
        TotalPembayaranCardLayout.setVerticalGroup(
            TotalPembayaranCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalPembayaranCardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jLabelTotalPembayaran)
                .addGap(22, 22, 22))
        );

        jPanelCardFrame.add(TotalPembayaranCard);

        Container.add(jPanelCardFrame, java.awt.BorderLayout.CENTER);

        jPanelContent.add(Container, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SidebarToggleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SidebarToggleButtonMouseClicked
        if (isSidebarVisible) {
            // Sembunyikan sidebar sepenuhnya dari layar
            SideBarPanel.setVisible(false);
            isSidebarVisible = false;
        } else {
            // Munculkan kembali sidebar ke layar
            SideBarPanel.setVisible(true);
            isSidebarVisible = true;
        }

        // Refresh layout Frame utama agar area putih langsung melebar otomatis
        this.revalidate();
        this.repaint();// TODO add your handling code here:
    }//GEN-LAST:event_SidebarToggleButtonMouseClicked

    private void btnLogout5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout5ActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout5ActionPerformed

    private void lblDashboard5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboard5MouseClicked

    }//GEN-LAST:event_lblDashboard5MouseClicked

    private void MenuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDashboardMouseClicked
        DashboardFormNew dashboard = new DashboardFormNew(penumpang);
        dashboard.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDashboardMouseClicked

    private void lblDashboardHitungTarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardHitungTarifMouseClicked
        HitungTarifFormNew h = new HitungTarifFormNew(penumpang);
        h.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lblDashboardHitungTarifMouseClicked

    private void MenuHitungTarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHitungTarifMouseClicked
        HitungTarifFormNew h = new HitungTarifFormNew(penumpang);
        h.setVisible(true);
        this.dispose();                // TODO add your handling code here:
    }//GEN-LAST:event_MenuHitungTarifMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CarbonSavingCard;
    private javax.swing.JPanel Container;
    private javax.swing.JPanel GreenPointCard;
    private javax.swing.JLabel JLabelUsername;
    private javax.swing.JPanel MenuDashboard;
    private javax.swing.JPanel MenuHitungTarif;
    private javax.swing.JPanel SideBarPanel;
    private javax.swing.JLabel SidebarToggleButton;
    private javax.swing.JPanel TotalPembayaranCard;
    private javax.swing.JButton btnLogout5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCarbonSaving;
    private javax.swing.JLabel jLabelGreenPoints;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelTotalPembayaran;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanelCardFrame;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeaderDashboard;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDashboard5;
    private javax.swing.JLabel lblDashboardHitungTarif;
    // End of variables declaration//GEN-END:variables
}
