/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import model.Penumpang;
import service.TransaksiManagerDB;

/**
 *
 * @author user
 */
public class DashboardFormNew extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFormNew.class.getName());

    /**
     * Creates new form DashboardFormNew
     */
    private final Penumpang penumpang;
    
    public DashboardFormNew(Penumpang penumpang) {
        initComponents();
        this.penumpang = penumpang;
        setLocationRelativeTo(null);
        tampilkanData();
    }
    
    private void tampilkanData() {
        jLabelUsername.setText("Selamat datang " + penumpang.getUsername());
        jLabelGreenPoints.setText(penumpang.getGreenPoints() + " PTS");

        double totalBayar = TransaksiManagerDB.totalBiaya(penumpang.getIdUser());
        double totalEmisi = TransaksiManagerDB.totalEmisi(penumpang.getIdUser());

        jLabelTotalPembayaran.setText("Rp " + String.format("%,.0f", totalBayar));
        jLabelCarbonSaving.setText(String.format("%.2f", totalEmisi) + " kg CO₂");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContent = new javax.swing.JPanel();
        jPanelHeaderDashboard = new javax.swing.JPanel();
        jLabelHeading = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelCardFrame = new javax.swing.JPanel();
        roundedPanel2 = new gui.RoundedPanel();
        roundedPanel5 = new gui.RoundedPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabelGreenPoints = new javax.swing.JLabel();
        roundedPanel3 = new gui.RoundedPanel();
        roundedPanel6 = new gui.RoundedPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelCarbonSaving = new javax.swing.JLabel();
        roundedPanel4 = new gui.RoundedPanel();
        roundedPanel7 = new gui.RoundedPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelTotalPembayaran = new javax.swing.JLabel();
        jButtonHitungTarif = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        jPanelContent.setBackground(new java.awt.Color(240, 244, 241));
        jPanelContent.setPreferredSize(new java.awt.Dimension(700, 293));

        jPanelHeaderDashboard.setBackground(java.awt.Color.white);
        jPanelHeaderDashboard.setPreferredSize(new java.awt.Dimension(700, 80));

        jLabelHeading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelHeading.setForeground(new java.awt.Color(27, 77, 62));
        jLabelHeading.setText("SmartFare Dashboard");

        jLabelUsername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(127, 140, 141));
        jLabelUsername.setText("Selamat datang User");

        jButton1.setBackground(new java.awt.Color(231, 76, 60));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(189, 195, 199));

        javax.swing.GroupLayout jPanelHeaderDashboardLayout = new javax.swing.GroupLayout(jPanelHeaderDashboard);
        jPanelHeaderDashboard.setLayout(jPanelHeaderDashboardLayout);
        jPanelHeaderDashboardLayout.setHorizontalGroup(
            jPanelHeaderDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderDashboardLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelHeaderDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHeading)
                    .addComponent(jLabelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(36, 36, 36))
            .addComponent(jSeparator1)
        );
        jPanelHeaderDashboardLayout.setVerticalGroup(
            jPanelHeaderDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderDashboardLayout.createSequentialGroup()
                .addGroup(jPanelHeaderDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHeaderDashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUsername))
                    .addGroup(jPanelHeaderDashboardLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelCardFrame.setBackground(new java.awt.Color(244, 246, 249));
        jPanelCardFrame.setPreferredSize(new java.awt.Dimension(700, 200));
        jPanelCardFrame.setLayout(new java.awt.GridLayout(1, 3, 25, 0));

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));

        roundedPanel5.setBackground(new java.awt.Color(233, 215, 165));
        roundedPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Green Points");

        jLabelGreenPoints.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelGreenPoints.setText("Points");

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGreenPoints)
                    .addComponent(jLabel5))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(52, 52, 52)
                .addComponent(jLabelGreenPoints)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCardFrame.add(roundedPanel2);

        roundedPanel3.setBackground(new java.awt.Color(255, 255, 255));

        roundedPanel6.setBackground(new java.awt.Color(163, 228, 215));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Carbon Saving");

        jLabelCarbonSaving.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelCarbonSaving.setText("Carbon");

        javax.swing.GroupLayout roundedPanel6Layout = new javax.swing.GroupLayout(roundedPanel6);
        roundedPanel6.setLayout(roundedPanel6Layout);
        roundedPanel6Layout.setHorizontalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel6Layout.createSequentialGroup()
                .addGroup(roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabelCarbonSaving))
                    .addGroup(roundedPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel6)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        roundedPanel6Layout.setVerticalGroup(
            roundedPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(55, 55, 55)
                .addComponent(jLabelCarbonSaving)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCardFrame.add(roundedPanel3);

        roundedPanel4.setBackground(new java.awt.Color(255, 255, 255));

        roundedPanel7.setBackground(new java.awt.Color(174, 214, 241));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Total Pembayaran");

        jLabelTotalPembayaran.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTotalPembayaran.setText("Pembayaran");

        javax.swing.GroupLayout roundedPanel7Layout = new javax.swing.GroupLayout(roundedPanel7);
        roundedPanel7.setLayout(roundedPanel7Layout);
        roundedPanel7Layout.setHorizontalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel7Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel7Layout.createSequentialGroup()
                        .addComponent(jLabelTotalPembayaran)
                        .addGap(26, 26, 26))))
        );
        roundedPanel7Layout.setVerticalGroup(
            roundedPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(51, 51, 51)
                .addComponent(jLabelTotalPembayaran)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelCardFrame.add(roundedPanel4);

        jButtonHitungTarif.setBackground(new java.awt.Color(30, 132, 73));
        jButtonHitungTarif.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButtonHitungTarif.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHitungTarif.setText("Hitung Tarif");
        jButtonHitungTarif.setPreferredSize(new java.awt.Dimension(200, 45));
        jButtonHitungTarif.addActionListener(this::jButtonHitungTarifActionPerformed);

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addGroup(jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHeaderDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelContentLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButtonHitungTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCardFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContentLayout.createSequentialGroup()
                .addComponent(jPanelHeaderDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCardFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonHitungTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHitungTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHitungTarifActionPerformed
        HitungTarifForm h = new HitungTarifForm(penumpang);
        h.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHitungTarifActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            // Membuat objek penumpang dummy/kosong agar constructor tidak error
//            model.Penumpang penumpangDummy = new model.Penumpang();
//            new DashboardFormNew(penumpangDummy).setVisible(true);
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonHitungTarif;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCarbonSaving;
    private javax.swing.JLabel jLabelGreenPoints;
    private javax.swing.JLabel jLabelHeading;
    private javax.swing.JLabel jLabelTotalPembayaran;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanelCardFrame;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeaderDashboard;
    private javax.swing.JSeparator jSeparator1;
    private gui.RoundedPanel roundedPanel2;
    private gui.RoundedPanel roundedPanel3;
    private gui.RoundedPanel roundedPanel4;
    private gui.RoundedPanel roundedPanel5;
    private gui.RoundedPanel roundedPanel6;
    private gui.RoundedPanel roundedPanel7;
    // End of variables declaration//GEN-END:variables
}
