/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import model.Penumpang;
import service.TransaksiManagerDB;
/**
 *
 * @author ASUS
 */
public class DashboardForm extends javax.swing.JFrame {

    private final Penumpang penumpang;

    public DashboardForm(Penumpang penumpang) {
        initComponents();
        this.penumpang = penumpang;
        setLocationRelativeTo(null);

        tampilkanData();
    }

    private void tampilkanData() {
        lblUsername.setText("Username: " + penumpang.getUsername());
        lblPoints.setText("Green Points: " + penumpang.getGreenPoints());

        double totalBayar = TransaksiManagerDB.totalBiaya(penumpang.getIdUser());
        double totalEmisi = TransaksiManagerDB.totalEmisi(penumpang.getIdUser());

        lblTotalPendapatan.setText("Total Pembayaran: Rp " + String.format("%,.0f", totalBayar));
        lblTotalEmisi.setText("Total Hemat Emisi: " + String.format("%.2f", totalEmisi) + " kg CO₂");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        lblPoints = new javax.swing.JLabel();
        btnHitungTarif = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblTotalPendapatan = new javax.swing.JLabel();
        lblTotalEmisi = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsername.setText("Nama");

        lblPoints.setText("Points");

        btnHitungTarif.setText("Hitung Tarif");
        btnHitungTarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungTarifActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblTotalPendapatan.setText("Total Pembayaran");

        lblTotalEmisi.setText("Total Emisi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalEmisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPoints, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnHitungTarif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                                .addComponent(btnLogout)))
                        .addGap(123, 123, 123))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsername)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblPoints)
                .addGap(18, 18, 18)
                .addComponent(lblTotalPendapatan)
                .addGap(18, 18, 18)
                .addComponent(lblTotalEmisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitungTarif)
                    .addComponent(btnLogout))
                .addGap(90, 90, 90))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungTarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungTarifActionPerformed
        HitungTarifForm h = new HitungTarifForm(penumpang);
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHitungTarifActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitungTarif;
    private javax.swing.JButton btnLogout;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblTotalEmisi;
    private javax.swing.JLabel lblTotalPendapatan;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
