/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import service.TransaksiManagerDB;
import model.Penumpang;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;



/**
 *
 * @author ASUS
 */


public class HistoriTransaksiForm extends javax.swing.JFrame {
    private Penumpang Penumpang;
    /**
     * Creates new form ManageTransaksiForm
     */
   public HistoriTransaksiForm(Penumpang Penumpang) {
    initComponents();

    this.Penumpang = Penumpang;

    setLocationRelativeTo(null);

    loadTransaksi();
}
    
    private void loadTransaksi() {

    DefaultTableModel model =
        (DefaultTableModel) tblTransaksi.getModel();

    model.setRowCount(0);

    try {

        ResultSet rs =
    TransaksiManagerDB.getAllTransaksi();

        while (rs.next()) {

            model.addRow(new Object[]{
                rs.getInt("id_transaksi"),
                new SimpleDateFormat("dd-MM-yyyy")
                .format(rs.getDate("tanggal")),
                rs.getString("username"),
                rs.getString("kendaraan"),
                rs.getString("kategori"),
                rs.getDouble("tarif"),
                rs.getDouble("emisi_hemat")
            });
        }

    } catch(Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        txtCariUser = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        sideBarPanel1 = new gui.SideBarPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtCariUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariUserActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tanggal", "Username", "Kendaraan", "Kategori", "Tarif", "Emisi"
            }
        ));
        jScrollPane1.setViewportView(tblTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnReset)
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtCariUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String username = txtCariUser.getText().trim();
String tanggal = txtTanggal.getText().trim();

if(username.isEmpty() && tanggal.isEmpty()){
    JOptionPane.showMessageDialog(
        this,
        "Masukkan username atau tanggal terlebih dahulu!"
    );
    return;
}
        
        DefaultTableModel model =
        (DefaultTableModel) tblTransaksi.getModel();

    model.setRowCount(0);

try {

    ResultSet rs = null;

    if(!username.isEmpty() && tanggal.isEmpty()) {

        rs = TransaksiManagerDB.searchByUsername(username);

    } else if(username.isEmpty() && !tanggal.isEmpty()) {

        rs = TransaksiManagerDB.searchByTanggal(tanggal);

    } else {

        rs = TransaksiManagerDB.searchTransaksi(
                username,
                tanggal
        );
    }

    while(rs.next()) {

        model.addRow(new Object[]{
            rs.getInt("id_transaksi"),
            new SimpleDateFormat("dd-MM-yyyy")
                .format(rs.getDate("tanggal")),
            rs.getString("username"),
            rs.getString("kendaraan"),
            rs.getString("kategori"),
            rs.getDouble("tarif"),
            rs.getDouble("emisi_hemat")
        });
    }

    if(model.getRowCount() == 0) {

        JOptionPane.showMessageDialog(
            this,
            "Data transaksi tidak ditemukan!"
        );
    }

} catch(Exception e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
    txtCariUser.setText("");
    txtTanggal.setText("");

    loadTransaksi();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtCariUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariUserActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private gui.SideBarPanel sideBarPanel1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtCariUser;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
