/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.awt.HeadlessException;
import java.util.Date;
import javax.swing.JOptionPane;
import model.*;
import service.CarbonCalculator;
import service.TransaksiManagerDB;
import service.UserManagerDB;


/**
 *
 * @author user
 */
public class HitungTarifFormNew extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFormNew.class.getName());
    
    private final Penumpang penumpang;

    public HitungTarifFormNew(Penumpang penumpang) {
        initComponents();
        this.penumpang = penumpang;
        setLocationRelativeTo(null);

        JLabelUsername.setText("" + penumpang.getUsername());
        cmbKendaraan.removeAllItems();
        cmbKendaraan.addItem("Angkot");
        cmbKendaraan.addItem("Bus");
        cmbKendaraan.addItem("Kereta");
        cmbKendaraan.addItem("Ojek Pangkalan");
        cmbKendaraan.addActionListener(e -> isiDetailKendaraan());

isiDetailKendaraan(); // pertama kali dijalankan

        cmbKategori.removeAllItems();
        cmbKategori.addItem("Umum");
        cmbKategori.addItem("Pelajar");
        cmbKategori.addItem("Lansia");

//        lblPoints.setText(String.valueOf(penumpang.getGreenPoints()));
    }

    private HitungTarifFormNew() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
      private Kendaraan buatObjekKendaraan(String jenis) {
        switch (jenis) {
            case "Angkot" -> {
                return new Angkot();
            }
            case "Bus" -> {
                return new Bus();
            }
            case "Kereta" -> {
                return new Kereta();
            }
            case "Ojek Pangkalan" -> {
                return new OjekPangkalan();
            }
        }
        return null;
    }

    private double diskonKategori(String kategori) {
        if (kategori.equals("Pelajar")) return 0.8;
        if (kategori.equals("Lansia")) return 0.7;
        return 1.0;
    }
    
    private void isiDetailKendaraan() {

    cmbDetailKendaraan.removeAllItems();

    String jenis = cmbKendaraan.getSelectedItem().toString();

    switch (jenis) {

        case "Angkot":
            cmbDetailKendaraan.addItem("Angkot Kota");
            cmbDetailKendaraan.addItem("Angkot Pedesaan");
            cmbDetailKendaraan.addItem("Lainnya");
            break;

        case "Bus":
            cmbDetailKendaraan.addItem("DAMRI");
            cmbDetailKendaraan.addItem("TransJakarta");
            cmbDetailKendaraan.addItem("Sinar Jaya");
            cmbDetailKendaraan.addItem("Rosalia Indah");
            cmbDetailKendaraan.addItem("Lainnya");
            break;

        case "Kereta":
            cmbDetailKendaraan.addItem("KRL");
            cmbDetailKendaraan.addItem("MRT");
            cmbDetailKendaraan.addItem("LRT");
            cmbDetailKendaraan.addItem("KA Jarak Jauh");
            cmbDetailKendaraan.addItem("Lainnya");
            break;

        case "Ojek Pangkalan":
            cmbDetailKendaraan.addItem("Pangkalan Terminal");
            cmbDetailKendaraan.addItem("Pangkalan Pasar");
            cmbDetailKendaraan.addItem("Pangkalan Stasiun");
            cmbDetailKendaraan.addItem("Lainnya");
            break;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SideBarPanel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnLogout5 = new javax.swing.JButton();
        MenuDashboard = new javax.swing.JPanel();
        lblDashboard5 = new javax.swing.JLabel();
        JLabelUsername = new javax.swing.JLabel();
        jLabelRole = new javax.swing.JLabel();
        MenuHitungTarif = new javax.swing.JPanel();
        lblDashboardHitungTarif = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbKendaraan = new javax.swing.JComboBox<>();
        txtJarak = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        cmbKategori = new javax.swing.JComboBox<>();
        txtHalte = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblDetailKendaraan = new javax.swing.JLabel();
        cmbDetailKendaraan = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabelLiveCard = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTarif = new javax.swing.JLabel();
        lblEta = new javax.swing.JLabel();
        lblEmisi = new javax.swing.JLabel();
        lblPoints = new javax.swing.JLabel();
        jPanelHeaderDashboard3 = new javax.swing.JPanel();
        jLabelHeading3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);

        jPanel11.setBackground(new java.awt.Color(0, 102, 51));

        btnLogout5.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout5.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout5.setText("Logout");
        btnLogout5.addActionListener(this::btnLogout5ActionPerformed);

        MenuDashboard.setBackground(new java.awt.Color(0, 102, 51));
        MenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDashboardMouseClicked(evt);
            }
        });

        lblDashboard5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDashboard5.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard5.setText("Dashboard");
        lblDashboard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboard5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuDashboardLayout = new javax.swing.GroupLayout(MenuDashboard);
        MenuDashboard.setLayout(MenuDashboardLayout);
        MenuDashboardLayout.setHorizontalGroup(
            MenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuDashboardLayout.setVerticalGroup(
            MenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JLabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        JLabelUsername.setText("User");

        jLabelRole.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelRole.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRole.setText("Selamat datang");

        MenuHitungTarif.setBackground(new java.awt.Color(0, 153, 102));
        MenuHitungTarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHitungTarifMouseClicked(evt);
            }
        });

        lblDashboardHitungTarif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDashboardHitungTarif.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboardHitungTarif.setText("Hitung Tarif");
        lblDashboardHitungTarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardHitungTarifMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuHitungTarifLayout = new javax.swing.GroupLayout(MenuHitungTarif);
        MenuHitungTarif.setLayout(MenuHitungTarifLayout);
        MenuHitungTarifLayout.setHorizontalGroup(
            MenuHitungTarifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHitungTarifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboardHitungTarif)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuHitungTarifLayout.setVerticalGroup(
            MenuHitungTarifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuHitungTarifLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDashboardHitungTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuHitungTarif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(JLabelUsername))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnLogout5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelRole)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(JLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRole)
                .addGap(17, 17, 17)
                .addComponent(MenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuHitungTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(btnLogout5)
                .addContainerGap())
        );

        javax.swing.GroupLayout SideBarPanelLayout = new javax.swing.GroupLayout(SideBarPanel);
        SideBarPanel.setLayout(SideBarPanelLayout);
        SideBarPanelLayout.setHorizontalGroup(
            SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SideBarPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SideBarPanelLayout.setVerticalGroup(
            SideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(SideBarPanel, java.awt.BorderLayout.WEST);

        jPanelContent.setBackground(new java.awt.Color(240, 244, 241));
        jPanelContent.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(240, 244, 241));
        jPanel1.setPreferredSize(new java.awt.Dimension(645, 345));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        jPanel2.setBackground(new java.awt.Color(102, 204, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Form Input");

        cmbKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKendaraan.addActionListener(this::cmbKendaraanActionPerformed);

        txtJarak.addActionListener(this::txtJarakActionPerformed);

        btnHitung.setText("Hitung Tarif");
        btnHitung.addActionListener(this::btnHitungActionPerformed);

        cmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan pilih kategori" }));

        txtHalte.addActionListener(this::txtHalteActionPerformed);

        jLabel1.setText("Jenis Kendaraan");

        jLabel8.setText("Jarak (KM)");

        jLabel9.setText("Jumlah Halte");

        jLabel10.setText("Kategori Pengguna");

        lblDetailKendaraan.setText("Detail Kendaraan");

        cmbDetailKendaraan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan pilih kendaraan" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtJarak, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(cmbDetailKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDetailKendaraan)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHalte, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDetailKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDetailKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJarak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHalte, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));

        jLabelLiveCard.setBackground(new java.awt.Color(255, 255, 255));
        jLabelLiveCard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelLiveCard.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLiveCard.setText("Hasil Kalkulasi");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tarif");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ETA");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Emisi");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Points");

        lblTarif.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTarif.setForeground(new java.awt.Color(255, 255, 255));
        lblTarif.setText("-");

        lblEta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEta.setForeground(new java.awt.Color(255, 255, 255));
        lblEta.setText("-");

        lblEmisi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmisi.setForeground(new java.awt.Color(255, 255, 255));
        lblEmisi.setText("-");

        lblPoints.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPoints.setForeground(new java.awt.Color(255, 255, 255));
        lblPoints.setText("-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoints)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(lblTarif)
                    .addComponent(lblEta)
                    .addComponent(jLabel5)
                    .addComponent(lblEmisi))
                .addContainerGap(291, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLiveCard)
                .addGap(104, 104, 104))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLiveCard)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTarif)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEta)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmisi)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPoints)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);

        jPanelContent.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanelHeaderDashboard3.setBackground(java.awt.Color.white);
        jPanelHeaderDashboard3.setPreferredSize(new java.awt.Dimension(700, 80));

        jLabelHeading3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelHeading3.setForeground(new java.awt.Color(27, 77, 62));
        jLabelHeading3.setText("Hitung Tarif Transportasi");

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(189, 195, 199));

        javax.swing.GroupLayout jPanelHeaderDashboard3Layout = new javax.swing.GroupLayout(jPanelHeaderDashboard3);
        jPanelHeaderDashboard3.setLayout(jPanelHeaderDashboard3Layout);
        jPanelHeaderDashboard3Layout.setHorizontalGroup(
            jPanelHeaderDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderDashboard3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabelHeading3)
                .addGap(36, 367, Short.MAX_VALUE))
            .addComponent(jSeparator2)
        );
        jPanelHeaderDashboard3Layout.setVerticalGroup(
            jPanelHeaderDashboard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderDashboard3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeading3)
                .addGap(38, 38, 38)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelContent.add(jPanelHeaderDashboard3, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private boolean isSidebarVisible = true;
    private void btnLogout5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout5ActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout5ActionPerformed

    private void lblDashboard5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboard5MouseClicked
 DashboardFormNew dashboard = new DashboardFormNew(penumpang);
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblDashboard5MouseClicked

    private void MenuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDashboardMouseClicked
        DashboardFormNew dashboard = new DashboardFormNew(penumpang);
        dashboard.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDashboardMouseClicked

    private void lblDashboardHitungTarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardHitungTarifMouseClicked
        HitungTarifFormNew h = new HitungTarifFormNew(penumpang);
        h.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_lblDashboardHitungTarifMouseClicked

    private void MenuHitungTarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHitungTarifMouseClicked
        HitungTarifFormNew h = new HitungTarifFormNew(penumpang);
        h.setVisible(true);
        this.dispose();        // TODO add your handling code here:                // TODO add your handling code here:
    }//GEN-LAST:event_MenuHitungTarifMouseClicked

    private void txtHalteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHalteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHalteActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        try {
            String jenis = cmbKendaraan.getSelectedItem().toString();
            String detailKendaraan = cmbDetailKendaraan.getSelectedItem().toString();
            String kategori = cmbKategori.getSelectedItem().toString();

            double jarak = Double.parseDouble(txtJarak.getText());
            int halte = Integer.parseInt(txtHalte.getText());

            if (jarak <= 0 || halte < 0) {
                JOptionPane.showMessageDialog(this, "Input tidak valid!");
                return;
            }

            Kendaraan kendaraan = buatObjekKendaraan(jenis);

            // override terjadi di sini
            double tarif = kendaraan.hitungTarif(jarak, halte);

            // diskon kategori (polymorphism penumpang)
            tarif = tarif * diskonKategori(kategori);

            double eta = kendaraan.hitungETA(jarak);

            // overload carbon calculator
            double emisiHemat = CarbonCalculator.hitungPenghematan(jarak, "mobil");

            int pointsBaru = (int) (emisiHemat * 10);
            penumpang.tambahPoints(pointsBaru);

            lblTarif.setText("Rp " + String.format("%.0f", tarif));
            lblEta.setText(String.format("%.2f jam", eta));
            lblEmisi.setText(String.format("%.2f kg CO2", emisiHemat));
            lblPoints.setText(String.valueOf(pointsBaru));

            // Bulatkan sebelum disimpan ke database
            tarif = Math.round(tarif * 100.0) / 100.0;
            eta = Math.round(eta * 100.0) / 100.0;
            emisiHemat = Math.round(emisiHemat * 100.0) / 100.0;

            // simpan transaksi
            Transaksi transaksi = new Transaksi(
                new Date(),
                jenis,
                detailKendaraan,
                kategori,
                jarak,
                halte,
                tarif,
                eta,
                emisiHemat
            );

            TransaksiManagerDB.tambahTransaksi(penumpang.getIdUser(), transaksi);
            UserManagerDB.updateGreenPoints(penumpang.getIdUser(), penumpang.getGreenPoints());

            JOptionPane.showMessageDialog(this, "Perhitungan berhasil!");

        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input harus berupa angka!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtJarakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJarakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJarakActionPerformed

    private void cmbKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKendaraanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HitungTarifFormNew().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelUsername;
    private javax.swing.JPanel MenuDashboard;
    private javax.swing.JPanel MenuHitungTarif;
    private javax.swing.JPanel SideBarPanel;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnLogout5;
    private javax.swing.JComboBox<String> cmbDetailKendaraan;
    private javax.swing.JComboBox<String> cmbKategori;
    private javax.swing.JComboBox<String> cmbKendaraan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHeading3;
    private javax.swing.JLabel jLabelLiveCard;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel jPanelHeaderDashboard3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDashboard5;
    private javax.swing.JLabel lblDashboardHitungTarif;
    private javax.swing.JLabel lblDetailKendaraan;
    private javax.swing.JLabel lblEmisi;
    private javax.swing.JLabel lblEta;
    private javax.swing.JLabel lblPoints;
    private javax.swing.JLabel lblTarif;
    private javax.swing.JTextField txtHalte;
    private javax.swing.JTextField txtJarak;
    // End of variables declaration//GEN-END:variables
}
