/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import model.Penumpang;

/**
 *
 * @author user
 */
public class SideBarPanel extends javax.swing.JPanel {

    /**
     * Creates new form SideBarPanel
     */
    // 1. Deklarasikan variabel penumpang di dalam class SideBarPanel
    private model.Penumpang penumpang; 

    // 2. Constructor default bawaan NetBeans
    public SideBarPanel() {
        initComponents();
    }
    
    // 3. BUAT CONSTRUCTOR BARU untuk menerima data penumpang
    public void setPenumpang(model.Penumpang penumpang) {
        this.penumpang = penumpang;
        
         JLabelUsername.setText(penumpang.getUsername()); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        btnLogout5 = new javax.swing.JButton();
        MenuDashboard = new javax.swing.JPanel();
        lblDashboard5 = new javax.swing.JLabel();
        JLabelUsername = new javax.swing.JLabel();
        jLabelRole = new javax.swing.JLabel();
        MenuHitungTarif = new javax.swing.JPanel();
        lblDashboardHitungTarif = new javax.swing.JLabel();
        MenuHistoriTransaksi = new javax.swing.JPanel();
        lblDashboard7 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(0, 102, 51));

        btnLogout5.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout5.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout5.setText("Logout");
        btnLogout5.addActionListener(this::btnLogout5ActionPerformed);

        MenuDashboard.setBackground(new java.awt.Color(0, 153, 102));
        MenuDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDashboardMouseClicked(evt);
            }
        });

        lblDashboard5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDashboard5.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard5.setText("Dashboard");
        lblDashboard5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboard5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuDashboardLayout = new javax.swing.GroupLayout(MenuDashboard);
        MenuDashboard.setLayout(MenuDashboardLayout);
        MenuDashboardLayout.setHorizontalGroup(
            MenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuDashboardLayout.setVerticalGroup(
            MenuDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuDashboardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDashboard5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JLabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        JLabelUsername.setText("Admin");

        jLabelRole.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelRole.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRole.setText("Selamat datang");

        MenuHitungTarif.setBackground(new java.awt.Color(0, 102, 51));
        MenuHitungTarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHitungTarifMouseClicked(evt);
            }
        });

        lblDashboardHitungTarif.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDashboardHitungTarif.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboardHitungTarif.setText("Hitung Tarif");
        lblDashboardHitungTarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboardHitungTarifMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuHitungTarifLayout = new javax.swing.GroupLayout(MenuHitungTarif);
        MenuHitungTarif.setLayout(MenuHitungTarifLayout);
        MenuHitungTarifLayout.setHorizontalGroup(
            MenuHitungTarifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHitungTarifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboardHitungTarif)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuHitungTarifLayout.setVerticalGroup(
            MenuHitungTarifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuHitungTarifLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDashboardHitungTarif, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuHistoriTransaksi.setBackground(new java.awt.Color(0, 102, 51));

        lblDashboard7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDashboard7.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboard7.setText("Riwayat");
        lblDashboard7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDashboard7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuHistoriTransaksiLayout = new javax.swing.GroupLayout(MenuHistoriTransaksi);
        MenuHistoriTransaksi.setLayout(MenuHistoriTransaksiLayout);
        MenuHistoriTransaksiLayout.setHorizontalGroup(
            MenuHistoriTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuHistoriTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboard7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuHistoriTransaksiLayout.setVerticalGroup(
            MenuHistoriTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuHistoriTransaksiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblDashboard7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenuDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuHitungTarif, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MenuHistoriTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(JLabelUsername))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnLogout5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelRole)))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(JLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRole)
                .addGap(17, 17, 17)
                .addComponent(MenuDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuHitungTarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuHistoriTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(btnLogout5)
                .addContainerGap())
        );

        add(jPanel11, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogout5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout5ActionPerformed
//        new LoginForm().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnLogout5ActionPerformed

    private void lblDashboard5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboard5MouseClicked

    }//GEN-LAST:event_lblDashboard5MouseClicked

    private void lblDashboardHitungTarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboardHitungTarifMouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_lblDashboardHitungTarifMouseClicked

    private void lblDashboard7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDashboard7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDashboard7MouseClicked

    private void MenuDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDashboardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDashboardMouseClicked

    private void MenuHitungTarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHitungTarifMouseClicked
        HitungTarifFormNew tarifForm = new HitungTarifFormNew(this.penumpang);
        tarifForm.setVisible(true);

        // 2. Cari JFrame induk yang sedang aktif menampung sidebar ini, lalu tutup
        javax.swing.JFrame parentFrame = (javax.swing.JFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame != null) {
            parentFrame.dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_MenuHitungTarifMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelUsername;
    private javax.swing.JPanel MenuDashboard;
    private javax.swing.JPanel MenuHistoriTransaksi;
    private javax.swing.JPanel MenuHitungTarif;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnLogout3;
    private javax.swing.JButton btnLogout4;
    private javax.swing.JButton btnLogout5;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDashboard1;
    private javax.swing.JLabel lblDashboard2;
    private javax.swing.JLabel lblDashboard3;
    private javax.swing.JLabel lblDashboard4;
    private javax.swing.JLabel lblDashboard5;
    private javax.swing.JLabel lblDashboard7;
    private javax.swing.JLabel lblDashboardHitungTarif;
    // End of variables declaration//GEN-END:variables
}
